{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cheny",
    "module": "ui",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 297901,
          "sha512": "8dfbdb089cf6f15592ead52347b73e6d5d578d28f46cbd6b92ac68b023ac65fa0474fa13a576a88755b31d760c7fca374c3c8b3a5ad1cb2c8af45343b55ccc72",
          "sha256": "352602c7aa49635ea9fe4da72b8276785cc3bd45c7040eab6f2504cba9998b5c",
          "sha1": "82490da068305b0f8ca2100638ee67e2fb639c6f",
          "md5": "919ce5e16e048cec9282a932d7f48631"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cheny",
          "module": "kit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 297901,
          "sha512": "8dfbdb089cf6f15592ead52347b73e6d5d578d28f46cbd6b92ac68b023ac65fa0474fa13a576a88755b31d760c7fca374c3c8b3a5ad1cb2c8af45343b55ccc72",
          "sha256": "352602c7aa49635ea9fe4da72b8276785cc3bd45c7040eab6f2504cba9998b5c",
          "sha1": "82490da068305b0f8ca2100638ee67e2fb639c6f",
          "md5": "919ce5e16e048cec9282a932d7f48631"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.0.0-sources.jar",
          "url": "ui-1.0.0-sources.jar",
          "size": 61323,
          "sha512": "7a6a61b10750f2ec2bf45ca74f3ecfe8a33f05ce2c758b89e1255d61e65f88cb336d9782d4777b94239ec1319200bb84dfc2472a8c4046941cef0ccd14906934",
          "sha256": "7719139f4c1b922e8b050bba80d0c2408498fec1ac49c89bb7fcf7a13795d2a5",
          "sha1": "3ca37000a21cdd4cd3378bbf840645aef34453e2",
          "md5": "ffa1d88a0c789dbf48fb22d4b3489028"
        }
      ]
    }
  ]
}
