{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cheny",
    "module": "kit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.0.aar",
          "url": "kit-1.0.0.aar",
          "size": 189511,
          "sha512": "12482ba683ff1a2ab638503d489508f5d714ce11728c3dc878645565c1bb07cb5ba16d5e7f77ad78dffb895553072550b25c1e03424490029497e4b48c752d97",
          "sha256": "b00e63b406582030a2fd2fdd7b354c30e86933d2a360af1a673fb2573c9a9f9a",
          "sha1": "432cb2a5f60c4ca8ee4fb80e1f60af5ee42c0785",
          "md5": "814358c67454c4f4580d090bd8f34f50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.0.aar",
          "url": "kit-1.0.0.aar",
          "size": 189511,
          "sha512": "12482ba683ff1a2ab638503d489508f5d714ce11728c3dc878645565c1bb07cb5ba16d5e7f77ad78dffb895553072550b25c1e03424490029497e4b48c752d97",
          "sha256": "b00e63b406582030a2fd2fdd7b354c30e86933d2a360af1a673fb2573c9a9f9a",
          "sha1": "432cb2a5f60c4ca8ee4fb80e1f60af5ee42c0785",
          "md5": "814358c67454c4f4580d090bd8f34f50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kit-1.0.0-sources.jar",
          "url": "kit-1.0.0-sources.jar",
          "size": 39904,
          "sha512": "0aafc3e4fa0e896b877d670c88a3e6841366cdc11e0a3211b5667cad71ec8fef4bd889ccdbdc76c85632c0287bca45c253aa8ac945142ec527770d107654cd51",
          "sha256": "d2147f4bcc88dde1f865afc1bf8386ecbdda25db0968cd19ca8cfceb9067207c",
          "sha1": "62d1ca4e73ee0ee32ce25f5e921f485be791cabe",
          "md5": "f9b9be0bd917d273e1a334b63d251f25"
        }
      ]
    }
  ]
}
